source 'http://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'rake'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'shotgun'
gem 'haml'
gem 'rack-flash3', :git => "git://github.com/treeder/rack-flash.git"
gem 'sendgrid'
gem 'actionmailer'
